services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped # Use 'unless-stopped' to keep Redis running unless explicitly stopped
    # ports:
    #   - "${REDIS_PORT}:${REDIS_INTERNAL_PORT}" # Do we need to expose Redis outside the Docker network?
    command: redis-server --port 6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    # network_mode: "host"

  backend:
    # image: hnguyenxzy/pcap-catalog-service:2.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${BE_EXPOSE_PORT}:8000"
    volumes:
      - "${PCAP_HOST_PCAP_DIRECTORY}:${PCAP_PCAP_DIRECTORY}"
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request, sys, os; url=f'http://localhost:8000/health'; urllib.request.urlopen(url)\""]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    # image: datrung/pcap-frontend-app:1.0.4
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${FE_EXPOSE_PORT}:80"
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:80 >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    # backend_logs:

networks:
  app_network:
    driver: bridge
